name: flutter_code_editor
description: A customizable code field supporting syntax highlighting, bi-directionnal scrolling and code modifiers
version: 0.1.0
homepage: https://github.com/akvelon/flutter-code-editor

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  autotrie: ^2.0.0
  charcode: ^1.3.1
  collection: ^1.16.0
  equatable: ^2.0.5
  flutter: { sdk: flutter }
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  linked_scroll_controller: ^0.2.0
  meta: ^1.7.0
  scrollable_positioned_list: ^0.2.3
  tuple: ^2.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^2.17.4

flutter:
  uses-material-design: true
  assets:
    - assets/keywords/
