name: flutter_code_editor
description: A customizable code field supporting syntax highlighting and code folding.
version: 0.3.2
repository: https://github.com/akvelon/flutter-code-editor

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  autotrie: ^2.0.0
  characters: ^1.2.1
  charcode: ^1.3.1
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter: { sdk: flutter }
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  http: ^1.1.0
  linked_scroll_controller: ^0.2.0
  meta: ^1.9.1
  mocktail: ^1.0.1
  scrollable_positioned_list: ^0.3.5
  tuple: ^2.0.1
  url_launcher: ^6.1.8

dev_dependencies:
  fake_async: ^1.3.1
  flutter_test: { sdk: flutter }
  total_lints: ^3.1.1

flutter:
  uses-material-design: true
